### ISSUE TITLE
Document things like '%import' and '%ignore'

### ISSUE THREAD

**Issue by Varriount** [erezsh/lark#15]
It doesn't appear that syntax features like '%import' and '%parse' are documented anywhere. This, plus the fact that there is no Python API reference, makes using lark more difficult than it should be.

**Comment by erezsh** [comment]
Good point, I'll add it to the reference.

What do you mean by "no Python API reference" ?

**Comment by erezsh** [comment]
Btw, there is no %parse, only %import and %ignore.

**Comment by Varriount** [comment]
Usually libraries like this have an API reference describing the public interface (like the documentation for the modules in Python's standard library).

**Comment by psboyce** [comment]
The [i?] options for strings and regexes should be documented in the same manner as well, I had to dig into the source code to figure out how to make a grammar case insensitive.

**Comment by erezsh** [comment]
What do you mean by the "?" option for strings and regexes ?

**Comment by psboyce** [comment]
Initially when I was trying to make my grammar case insensitive I was trying to do something like this;

    int_stmnt: "INT"i? _WS+ INT
    _EXP: /e[+-]?[0-9]+/i?

I knew that prefixing regexes with (?i) would make them case insensitive with most regex engines, so I thought I needed to append "i?" to make the regex insensitive. It turns out that "i" and "?" are exclusive; "i" will make the string/regex case insensitive and "?" will match the string/regex zero or one times, which doesn't quite do what I intended.

**Comment by erezsh** [comment]
Documented here https://github.com/erezsh/lark/wiki/Grammar-Reference
