### ISSUE TITLE
Except symbol supported?

### ISSUE THREAD

**Issue by mihailefter** [erezsh/lark#96]
I don't know if this is the right place to ask this (btw, is there any forum available?), but is the except symbol supported by Lark? Something as `NotAny('abc')` in pyparsing?

Another question: how close/far is the grammar compared to the EBNF ISO standard?
http://www.cl.cam.ac.uk/~mgk25/iso-14977.pdf

**Comment by erezsh** [comment]
There is no forum, but perhaps I should open one.

Lark doesn't have a "NotAny" opreator, in terms of a parse-level assert. But you can get a similar effect using regular expressions, in some situations. There is the `(?!negative-lookahead)` operator, which is very similar to pyparsing's NotAny, but it's attached to a specific terminal. There is also the `[^negative-char-match]` operator, which is sometimes useful. If you explain your use-case perhaps we can think of a solution that fits.

Lark's syntax is a little different than what the ISO describes, and it leaves some key features to regexps, such as "special characters", instead of reinventing the wheel. Personally I think Lark's syntax is a little more consistent and easier to read. It's definitely shorter, and requires less "meta-characters".

**Comment by erezsh** [comment]
Btw, just created https://groups.google.com/forum/#!forum/lark-parser

We'll see if it takes off :)

**Comment by mihailefter** [comment]
Thanks for your quick reply @erezsh.

We are writing a grammar that we would like to be as standard as possible such that it could be used by different lark alike libraries in different programming languages to generate the required parsers. For this reason we would like to avoid custom EBNF syntax. We could write the grammar using the 'lark' specific syntax though, but it would be nice if there is any way of rewriting back the grammar file with some changes, such that 'lark' specifics can be then removed. Do you know if this is possible?

For the `NotAny`, we have for example the following rule:

    rule = NotAny('TEMP_') + Combine(Word(alphas + '_') + Number)

Another question: is there any method equivalent to `pydot__tree_to_png`that would make the railroad syntax diagram of the grammar? Or some tree based alternative image?

**Comment by erezsh** [comment]
Sure, it's possible. You can write a formal EBNF parser that will generate a Lark grammar. I imagine it's straightforward enough to be done in an hour or two.

Your NotAny rule can be written this way (don't mind the specifics):

TERM: /(?!TEMP_)[A-Za-z_]\d+/

Lark has no such method for railroad diagrams. But if you're already parsing EBNF, you can probably "compile" it for https://github.com/tabatkins/railroad-diagrams, or something similar.

**Comment by mihailefter** [comment]
Thanks @erezsh.

Maybe we should move to the forum now :)
